/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package md.autoservice.serviceauto.gui;

import javax.swing.ListSelectionModel;
import md.autoservice.serviceauto.gui.models.AngajatiCheckBoxTableModel;
import md.autoservice.serviceauto.model.Reparatie;
import md.autoservice.serviceauto.util.ReparatiNotFoundException;

/**
 *
 * @author iucosoft5
 */
public class ListaReparatorilorDialog extends javax.swing.JDialog {

    private final Reparatie reparatii;
    private AngajatiCheckBoxTableModel cbtm;
    private static ReparatiiDialog parentFrame;

    public ListaReparatorilorDialog(ReparatiiDialog parentFrame, boolean modal, Reparatie reparati) throws ReparatiNotFoundException {
        this.parentFrame = parentFrame;
        this.reparatii = reparati;
        
        setModal(modal);
        initComponents();
        initModels();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPaneCheckBoxAngajati = new javax.swing.JScrollPane();
        jTableAngajatiChckBox = new javax.swing.JTable();
        jButtonSaveListaAngajati = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 51));
        setForeground(new java.awt.Color(255, 153, 51));

        jTableAngajatiChckBox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTableAngajatiChckBox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneCheckBoxAngajati.setViewportView(jTableAngajatiChckBox);

        jButtonSaveListaAngajati.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonSaveListaAngajati.setText("Save");
        jButtonSaveListaAngajati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveListaAngajatiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jButtonSaveListaAngajati, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addComponent(jScrollPaneCheckBoxAngajati, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPaneCheckBoxAngajati, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonSaveListaAngajati)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveListaAngajatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveListaAngajatiActionPerformed

        parentFrame.refreshAngajatiSelectatiTableModel(cbtm.getAngajatiSelectati());
        this.dispose();

    }//GEN-LAST:event_jButtonSaveListaAngajatiActionPerformed

    private void initModels() throws ReparatiNotFoundException {
        cbtm = new AngajatiCheckBoxTableModel(reparatii);
        jTableAngajatiChckBox.setModel(cbtm);
        jTableAngajatiChckBox.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSaveListaAngajati;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneCheckBoxAngajati;
    private javax.swing.JTable jTableAngajatiChckBox;
    // End of variables declaration//GEN-END:variables

}
