/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package md.autoservice.serviceauto.gui;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import md.autoservice.serviceauto.dao.AngajatDaoIntf;
import md.autoservice.serviceauto.dao.MasiniDaoIntf;
import md.autoservice.serviceauto.dao.ProprietarDaoIntf;
import md.autoservice.serviceauto.dao.ReparatiDaoIntf;
import md.autoservice.serviceauto.dao.ReparatieAngajatDaoIntf;
import md.autoservice.serviceauto.dao.impl.AngajatDaoImpl;
import md.autoservice.serviceauto.dao.impl.MasiniDaoImpl;
import md.autoservice.serviceauto.dao.impl.ProprietarDaoImpl;
import md.autoservice.serviceauto.dao.impl.ReparatiDaoImpl;
import md.autoservice.serviceauto.dao.impl.ReparatieAngajatDaoImpl;
import md.autoservice.serviceauto.db.MyDataSource;
import md.autoservice.serviceauto.gui.models.ReparatiTableModel;
import md.autoservice.serviceauto.model.Angajat;
import md.autoservice.serviceauto.model.Masina;
import md.autoservice.serviceauto.model.Proprietar;
import md.autoservice.serviceauto.model.Reparatie;
import md.autoservice.serviceauto.service.MasinaProprietarDaoIntf;
import md.autoservice.serviceauto.service.impl.MasinaProprietarDaoImpl;
import md.autoservice.serviceauto.util.AngajatNotFoundException;
import md.autoservice.serviceauto.util.MyUtil;
import md.autoservice.serviceauto.util.ReparatiNotFoundException;

/**
 *
 * @author valera_
 */
public class MasinaDialog extends javax.swing.JDialog {

    private Angajat angajat;
    private Masina masina;
    private Reparatie reparatie;
    private final Proprietar proprietar;
    private final MainJFrame parenFrame;
    private final MasiniDaoIntf masiniDao;
    private final AngajatDaoIntf angajatDao;
    private final ReparatiDaoIntf reparatiDao;
    private ReparatiTableModel reparatiTableModel;
    private final ProprietarDaoIntf proprietarDao;
    private final MasinaProprietarDaoIntf masinaService;
    private final ReparatieAngajatDaoIntf reparatieAngajatDao;

    public MasinaDialog(MainJFrame parentFrame, boolean modal, Masina masina) {
        setTitle("Masini - REPARATII APP");
        this.parenFrame = parentFrame;
        setModal(modal);
        this.masina = masina;
        reparatie = new Reparatie();
        reparatiDao = new ReparatiDaoImpl();
        masinaService = new MasinaProprietarDaoImpl();
        reparatieAngajatDao = new ReparatieAngajatDaoImpl();
        masiniDao = new MasiniDaoImpl();
        proprietar = new Proprietar();
        proprietarDao = new ProprietarDaoImpl();
        angajat = new Angajat();
        angajatDao = new AngajatDaoImpl();
        initComponents();
        fillForm();
        setModels();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableReparatii = new javax.swing.JTable();
        jButtonAddReparatie = new javax.swing.JButton();
        jButtonEditReparatie = new javax.swing.JButton();
        jButtonDeleteReparatie = new javax.swing.JButton();
        jButtonMasinaSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldModelMotor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNrInmatriculare = new javax.swing.JTextField();
        jComboBoxCombustibil = new javax.swing.JComboBox();
        jTextFieldModel = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jSpinnerAnu = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldProprietarNume = new javax.swing.JTextField();
        jTextFieldProprietarPrenume = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldProprietarTelefon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela reparatiilor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jTableReparatii.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTableReparatii.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableReparatii.setGridColor(new java.awt.Color(255, 204, 0));
        jTableReparatii.setSelectionForeground(new java.awt.Color(255, 204, 0));
        jScrollPane2.setViewportView(jTableReparatii);

        jButtonAddReparatie.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonAddReparatie.setText("Adauga ");
        jButtonAddReparatie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddReparatieActionPerformed(evt);
            }
        });

        jButtonEditReparatie.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonEditReparatie.setText("Edit");
        jButtonEditReparatie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditReparatieActionPerformed(evt);
            }
        });

        jButtonDeleteReparatie.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonDeleteReparatie.setText("Delete ");
        jButtonDeleteReparatie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteReparatieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEditReparatie)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButtonAddReparatie))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDeleteReparatie)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAddReparatie, jButtonDeleteReparatie, jButtonEditReparatie});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonAddReparatie)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditReparatie)
                .addGap(27, 27, 27)
                .addComponent(jButtonDeleteReparatie)
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jButtonMasinaSave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonMasinaSave.setText("Save");
        jButtonMasinaSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasinaSaveActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informatii masina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Model motor");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Marca");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Anul");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Model");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Nr inmatriculare");

        jComboBoxCombustibil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecteaza", "Benzin", "Disel", "Gaz", "Gaz/Benzin" }));

        jSpinnerAnu.setModel(new javax.swing.SpinnerNumberModel(1950, 1950, 2014, 1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Combustibil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldModelMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jTextFieldNrInmatriculare, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerAnu, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxCombustibil, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNrInmatriculare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerAnu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxCombustibil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldModelMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informatii proprietar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Prenume");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Nume");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Nr. telefon");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("E-mail");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldProprietarPrenume, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jTextFieldProprietarNume)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldProprietarTelefon)
                            .addComponent(jTextFieldEmail))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldProprietarNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldProprietarPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProprietarTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButtonMasinaSave, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMasinaSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMasinaSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasinaSaveActionPerformed

        //proprietar = masina.getProprietar();
        /// proprietar = new Proprietar();
        getDateMasinaProprietar();
        try {
            String word = "";
            if (masina.getId() < 1) {
                masinaService.save(masina);
                word = "adaugata";
            } else {// update
                masinaService.update(masina);
                word = "editata";
            }
            JOptionPane.showMessageDialog(this, "Masina " + word + " cu success", "Info",
                    JOptionPane.INFORMATION_MESSAGE);

            parenFrame.masiniPanel.refreshMasiniTable();

            masina = null;

            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(MasinaDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonMasinaSaveActionPerformed

    private void jButtonDeleteReparatieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteReparatieActionPerformed

        int row = jTableReparatii.getSelectedRow();
        if (row != -1) {
            int reparatieId = (Integer) jTableReparatii.getValueAt(row, 0);// 0 -0 prima coloana
            try {
                reparatie = reparatiDao.findById(reparatieId);

                int rez = JOptionPane.showConfirmDialog(this, "esti sigur vrei sa sterg reparatia?",
                        "Question", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                switch (rez) {
                    case JOptionPane.YES_OPTION:

                        reparatieAngajatDao.delete(reparatie.getId());
                        reparatiDao.delete(reparatie);

                        JOptionPane.showMessageDialog(this, "Reparatie sters cu success", "Succes",
                                JOptionPane.INFORMATION_MESSAGE);
                        break;
                    case JOptionPane.NO_OPTION:
                    case JOptionPane.CLOSED_OPTION:
                        break;
                }
            } catch (ReparatiNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Reparatia nu este gasit cu id=" + reparatieId,
                        "Error", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(LucratoriPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(LucratoriPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            refreshMasiniTable();
        } else {
            JOptionPane.showMessageDialog(this, "Selectati reparatia!",
                    "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteReparatieActionPerformed

    private void jButtonAddReparatieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddReparatieActionPerformed
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReparatiiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReparatiiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReparatiiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReparatiiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ReparatiiDialog dialog;
                try {
                    String word = "";
                    if (masina.getId() < 1) {
                        Connection conn = MyDataSource.getInstace().getConnection();
                        getDateMasinaProprietar();
                        masinaService.save(masina);
                        masina.setId(MyUtil.getMaxId(conn, "masini"));
                        parenFrame.masiniPanel.refreshMasiniTable();
                    }
                } catch (Exception ex) {
                    Logger.getLogger(MasinaDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog = new ReparatiiDialog(MasinaDialog.this, true, new Reparatie(), masina);
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonAddReparatieActionPerformed

    private void jButtonEditReparatieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditReparatieActionPerformed

        int row = jTableReparatii.getSelectedRow();

        if (row != -1) {
            int id = (Integer) reparatiTableModel.getValueAt(row, 0);// 0 -0 prima coloana
            try {
                reparatie = reparatiDao.findById(id);

                List<Integer> listaIdAngajatiSelectati = new ArrayList<>();
                List<Angajat> listaAngajatiSelectati = new ArrayList<>();

                listaIdAngajatiSelectati = reparatieAngajatDao.findAllByIdReparati(reparatie.getId());
                for (Integer idAngajat : listaIdAngajatiSelectati) {
                    angajat = angajatDao.findById(idAngajat);
                    listaAngajatiSelectati.add(angajat);
                }
                reparatie.setListaReparatori(listaAngajatiSelectati);

            } catch (ReparatiNotFoundException ex) {
                Logger.getLogger(MasinaDialog.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Masina nu este gasita cu id=" + id,
                        "Error", JOptionPane.WARNING_MESSAGE);
                return;
            } catch (AngajatNotFoundException ex) {
                Logger.getLogger(MasinaDialog.class.getName()).log(Level.SEVERE, null, ex);
            }

            showReparatiiDialog();
        } else {
            JOptionPane.showMessageDialog(this, "Selectati reparatia!",
                    "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEditReparatieActionPerformed

    private void setModels() {
        refreshMasiniTable();
    }

    void refreshMasiniTable() {
        //  System.out.println("Id masina =  " + masina.getId());
        reparatiTableModel = new ReparatiTableModel(masina.getId());
        jTableReparatii.setModel(reparatiTableModel);
        jTableReparatii.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void fillForm() {
        if (masina.getId() != 0) {

            jTextFieldNrInmatriculare.setText(masina.getNrInmatriculare());
            jTextFieldMarca.setText(masina.getMarca());
            jTextFieldModel.setText(masina.getModel());
            jSpinnerAnu.setValue(masina.getAnu());
            jComboBoxCombustibil.setSelectedItem(masina.getCombustibil());
            jTextFieldModelMotor.setText(masina.getModelMotor());

            if (masina.getProprietar() != null) {
                jTextFieldProprietarNume.setText(masina.getProprietar().getNume());
                jTextFieldProprietarPrenume.setText(masina.getProprietar().getPrenume());
                jTextFieldProprietarTelefon.setText(String.valueOf(masina.getProprietar().getNrTelefon()));
                jTextFieldEmail.setText(masina.getProprietar().getEmail());
            }

        }
    }

    private void getDateMasinaProprietar() {

        proprietar.setNume(jTextFieldProprietarNume.getText());
        proprietar.setPrenume(jTextFieldProprietarPrenume.getText());
        proprietar.setNrTelefon(new Integer(jTextFieldProprietarTelefon.getText()));
        proprietar.setEmail(jTextFieldEmail.getText());

        masina.setNrInmatriculare(jTextFieldNrInmatriculare.getText());
        masina.setMarca(jTextFieldMarca.getText());
        masina.setModel(jTextFieldModel.getText());
        masina.setAnu((int) jSpinnerAnu.getValue());
        masina.setCombustibil((String) jComboBoxCombustibil.getSelectedItem());
        masina.setModelMotor(jTextFieldModelMotor.getText());
        masina.setProprietar(proprietar);

    }

    private void showReparatiiDialog() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReparatiiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReparatiiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReparatiiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReparatiiDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ReparatiiDialog dialog;

                if (reparatie == null) {
                    JOptionPane.showMessageDialog(parenFrame, reparatie);
                }
                dialog = new ReparatiiDialog(MasinaDialog.this, true, reparatie, masina);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddReparatie;
    private javax.swing.JButton jButtonDeleteReparatie;
    private javax.swing.JButton jButtonEditReparatie;
    private javax.swing.JButton jButtonMasinaSave;
    private javax.swing.JComboBox jComboBoxCombustibil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerAnu;
    private javax.swing.JTable jTableReparatii;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldModelMotor;
    private javax.swing.JTextField jTextFieldNrInmatriculare;
    private javax.swing.JTextField jTextFieldProprietarNume;
    private javax.swing.JTextField jTextFieldProprietarPrenume;
    private javax.swing.JTextField jTextFieldProprietarTelefon;
    // End of variables declaration//GEN-END:variables

}
